/**
 * @file Version.h
 * @brief Version information for MB85RC.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef MB85RC_VERSION_STRING
#define MB85RC_VERSION_STRING "1.0.0"
#endif

#ifndef MB85RC_BUILD_DATE
#define MB85RC_BUILD_DATE __DATE__
#endif

#ifndef MB85RC_BUILD_TIME
#define MB85RC_BUILD_TIME __TIME__
#endif

#ifndef MB85RC_BUILD_TIMESTAMP
#define MB85RC_BUILD_TIMESTAMP MB85RC_BUILD_DATE " " MB85RC_BUILD_TIME
#endif

#ifndef MB85RC_GIT_COMMIT
#define MB85RC_GIT_COMMIT "unknown"
#endif

#ifndef MB85RC_GIT_STATUS
#define MB85RC_GIT_STATUS "unknown"
#endif

#ifndef MB85RC_VERSION_FULL
#define MB85RC_VERSION_FULL MB85RC_VERSION_STRING " (" MB85RC_GIT_COMMIT ", " MB85RC_BUILD_TIMESTAMP ", " MB85RC_GIT_STATUS ")"
#endif

namespace MB85RC {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = MB85RC_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10000;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10000;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = MB85RC_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = MB85RC_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = MB85RC_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = MB85RC_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = MB85RC_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = MB85RC_VERSION_FULL;

}  // namespace MB85RC
